spring.application.name=shecare

# Cloud SQL MySQL
spring.datasource.url=jdbc:mysql:///shecare-database?cloudSqlInstance=echory-32cd7:asia-south1:shecare-new&socketFactory=com.google.cloud.sql.mysql.SocketFactory
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# AI Service
ai.service.url=${AI_SERVICE_URL}

server.port=${PORT:8080}